CREATE DATABASE IF NOT EXISTS amanverma;
CREATE DATABASE IF NOT EXISTS INSTAGRAM;
CREATE DATABASE IF NOT EXISTS Youtube;

DROP DATABASE IF EXISTS INSTAGRAM;

SHOW DATABASES;

USE amanverma;

CREATE TABLE information(
name VARCHAR(25),
age int,
College VARCHAR(100),
City VARCHAR(25)
);

SHOW TABLES;